import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  home,
  homeOutline,
  business,
  businessOutline,
  construct,
  constructOutline,
  calendar,
  calendarOutline,
  hammer,
  hammerOutline,
  analytics,
  add,
  addOutline,
  peopleOutline,
  person,
  personOutline,
  documentsOutline,
  checkmarkCircleOutline,
  cashOutline,
  timeOutline,
  warningOutline,
  copyOutline,
  trashOutline,
  trash,
  alertCircle,
  refresh,
  eye,
  eyeOutline,
  eyeOffOutline,
  create,
  createOutline,
  cash,
  arrowBack,
  arrowBackOutline,
  chevronBack,
  chevronForward,
  chevronDownCircleOutline,
  close,
  closeCircle,
  closeOutline,
  informationCircleOutline,
  layersOutline,
  locationOutline,
  mailOutline,
  callOutline,
  cameraOutline,
  cardOutline,
  settingsOutline,
  archiveOutline,
  checkmark,
  list,
  camera,
  moon,
  lockClosedOutline,
  logoGoogle,
  saveOutline,
  logOutOutline,
  cubeOutline,
  swapVertical,
  arrowDown,
  arrowUp,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  constructor() {
    // Register all icons used throughout the app globally
    addIcons({
      home,
      'home-outline': homeOutline,
      'house-outline': homeOutline, // Alias for home-outline
      business,
      'business-outline': businessOutline,
      construct,
      'construct-outline': constructOutline,
      calendar,
      'calendar-outline': calendarOutline,
      hammer,
      'hammer-outline': hammerOutline,
      analytics,
      add,
      'add-outline': addOutline,
      'people-outline': peopleOutline,
      person,
      'person-outline': personOutline,
      'documents-outline': documentsOutline,
      'checkmark-circle-outline': checkmarkCircleOutline,
      'cash-outline': cashOutline,
      'time-outline': timeOutline,
      'warning-outline': warningOutline,
      'copy-outline': copyOutline,
      'trash-outline': trashOutline,
      trash,
      'alert-circle': alertCircle,
      refresh,
      eye,
      'eye-outline': eyeOutline,
      'eye-off-outline': eyeOffOutline,
      create,
      'create-outline': createOutline,
      cash,
      'arrow-back': arrowBack,
      'arrow-back-outline': arrowBackOutline,
      'chevron-back': chevronBack,
      'chevron-forward': chevronForward,
      'chevron-down-circle-outline': chevronDownCircleOutline,
      close,
      'close-circle': closeCircle,
      'close-outline': closeOutline,
      'information-circle-outline': informationCircleOutline,
      'layers-outline': layersOutline,
      'location-outline': locationOutline,
      'mail-outline': mailOutline,
      'call-outline': callOutline,
      'camera-outline': cameraOutline,
      'card-outline': cardOutline,
      'settings-outline': settingsOutline,
      'archive-outline': archiveOutline,
      checkmark,
      list,
      camera,
      moon,
      'lock-closed-outline': lockClosedOutline,
      'logo-google': logoGoogle,
      'save-outline': saveOutline,
      'log-out-outline': logOutOutline,
      'cube-outline': cubeOutline,
      'swap-vertical': swapVertical,
      'arrow-down': arrowDown,
      'arrow-up': arrowUp,
    });
  }
}
